//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFT.Trainer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EFT.Trainer.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dump.
        /// </summary>
        internal static string CommandDump {
            get {
                return ResourceManager.GetString("CommandDump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dumping game objects....
        /// </summary>
        internal static string CommandDumpGameObjects {
            get {
                return ResourceManager.GetString("CommandDumpGameObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dumping Scenes....
        /// </summary>
        internal static string CommandDumpScenes {
            get {
                return ResourceManager.GetString("CommandDumpScenes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dump created in {0}.
        /// </summary>
        internal static string CommandDumpSuccessFormat {
            get {
                return ResourceManager.GetString("CommandDumpSuccessFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to list.
        /// </summary>
        internal static string CommandList {
            get {
                return ResourceManager.GetString("CommandList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} [{1}] {2}.
        /// </summary>
        internal static string CommandListEnumerateFormat {
            get {
                return ResourceManager.GetString("CommandListEnumerateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to listr.
        /// </summary>
        internal static string CommandListRare {
            get {
                return ResourceManager.GetString("CommandListRare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}).
        /// </summary>
        internal static string CommandListRarityFormat {
            get {
                return ResourceManager.GetString("CommandListRarityFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} item(s).
        /// </summary>
        internal static string CommandListSuccessFormat {
            get {
                return ResourceManager.GetString("CommandListSuccessFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to listsr.
        /// </summary>
        internal static string CommandListSuperRare {
            get {
                return ResourceManager.GetString("CommandListSuperRare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load settings.
        /// </summary>
        internal static string CommandLoadDescription {
            get {
                return ResourceManager.GetString("CommandLoadDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to load.
        /// </summary>
        internal static string CommandLoadName {
            get {
                return ResourceManager.GetString("CommandLoadName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded {0}.
        /// </summary>
        internal static string CommandLoadSuccessFormat {
            get {
                return ResourceManager.GetString("CommandLoadSuccessFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loadtl.
        /// </summary>
        internal static string CommandLoadTrackList {
            get {
                return ResourceManager.GetString("CommandLoadTrackList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save settings.
        /// </summary>
        internal static string CommandSaveDescription {
            get {
                return ResourceManager.GetString("CommandSaveDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be careful when updating this file :)
        ///For keys, use https://docs.unity3d.com/ScriptReference/KeyCode.html
        ///Colors are stored as an array of &apos;RGBA&apos; floats.
        /// </summary>
        internal static string CommandSaveHeader {
            get {
                return ResourceManager.GetString("CommandSaveHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        internal static string CommandSaveName {
            get {
                return ResourceManager.GetString("CommandSaveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved {0}.
        /// </summary>
        internal static string CommandSaveSuccessFormat {
            get {
                return ResourceManager.GetString("CommandSaveSuccessFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to savetl.
        /// </summary>
        internal static string CommandSaveTrackList {
            get {
                return ResourceManager.GetString("CommandSaveTrackList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spawn.
        /// </summary>
        internal static string CommandSpawn {
            get {
                return ResourceManager.GetString("CommandSpawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spawnbot.
        /// </summary>
        internal static string CommandSpawnBot {
            get {
                return ResourceManager.GetString("CommandSpawnBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string CommandSpawnBotEnumerateFormat {
            get {
                return ResourceManager.GetString("CommandSpawnBotEnumerateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spawnhi.
        /// </summary>
        internal static string CommandSpawnHideoutItems {
            get {
                return ResourceManager.GetString("CommandSpawnHideoutItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spawnqi.
        /// </summary>
        internal static string CommandSpawnQuestItems {
            get {
                return ResourceManager.GetString("CommandSpawnQuestItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to status.
        /// </summary>
        internal static string CommandStatus {
            get {
                return ResourceManager.GetString("CommandStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is {1} {2}.
        /// </summary>
        internal static string CommandStatusTextFormat {
            get {
                return ResourceManager.GetString("CommandStatusTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0} to toggle).
        /// </summary>
        internal static string CommandStatusTextToggleFormat {
            get {
                return ResourceManager.GetString("CommandStatusTextToggleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to template.
        /// </summary>
        internal static string CommandTemplate {
            get {
                return ResourceManager.GetString("CommandTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1} [{2}].
        /// </summary>
        internal static string CommandTemplateEnumerateFormat {
            get {
                return ResourceManager.GetString("CommandTemplateEnumerateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} template(s).
        /// </summary>
        internal static string CommandTemplateSuccessFormat {
            get {
                return ResourceManager.GetString("CommandTemplateSuccessFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to track.
        /// </summary>
        internal static string CommandTrack {
            get {
                return ResourceManager.GetString("CommandTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tracklist.
        /// </summary>
        internal static string CommandTrackList {
            get {
                return ResourceManager.GetString("CommandTrackList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking: {0} {1}.
        /// </summary>
        internal static string CommandTrackListEnumerateFormat {
            get {
                return ResourceManager.GetString("CommandTrackListEnumerateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}).
        /// </summary>
        internal static string CommandTrackListRarityFormat {
            get {
                return ResourceManager.GetString("CommandTrackListRarityFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking list updated....
        /// </summary>
        internal static string CommandTrackListUpdated {
            get {
                return ResourceManager.GetString("CommandTrackListUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking: {0} (Wishlist).
        /// </summary>
        internal static string CommandTrackListWishListEnumerateFormat {
            get {
                return ResourceManager.GetString("CommandTrackListWishListEnumerateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trackr.
        /// </summary>
        internal static string CommandTrackRare {
            get {
                return ResourceManager.GetString("CommandTrackRare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tracksr.
        /// </summary>
        internal static string CommandTrackSuperRare {
            get {
                return ResourceManager.GetString("CommandTrackSuperRare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to untrack.
        /// </summary>
        internal static string CommandUnTrack {
            get {
                return ResourceManager.GetString("CommandUnTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patched {0} with {1}.
        /// </summary>
        internal static string DebugPatchedMethodFormat {
            get {
                return ResourceManager.GetString("DebugPatchedMethodFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshed {0} in {1}ms.
        /// </summary>
        internal static string DebugPerformanceRefreshedFormat {
            get {
                return ResourceManager.GetString("DebugPerformanceRefreshedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering {0} command....
        /// </summary>
        internal static string DebugRegisteringCommandFormat {
            get {
                return ResourceManager.GetString("DebugRegisteringCommandFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering {0} command with arguments....
        /// </summary>
        internal static string DebugRegisteringCommandWithArgumentsFormat {
            get {
                return ResourceManager.GetString("DebugRegisteringCommandWithArgumentsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E.
        /// </summary>
        internal static string DirectionEast {
            get {
                return ResourceManager.GetString("DirectionEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.
        /// </summary>
        internal static string DirectionNorth {
            get {
                return ResourceManager.GetString("DirectionNorth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NE.
        /// </summary>
        internal static string DirectionNorthEast {
            get {
                return ResourceManager.GetString("DirectionNorthEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NW.
        /// </summary>
        internal static string DirectionNorthWest {
            get {
                return ResourceManager.GetString("DirectionNorthWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        internal static string DirectionSouth {
            get {
                return ResourceManager.GetString("DirectionSouth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SE.
        /// </summary>
        internal static string DirectionSouthEast {
            get {
                return ResourceManager.GetString("DirectionSouthEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SW.
        /// </summary>
        internal static string DirectionSouthWest {
            get {
                return ResourceManager.GetString("DirectionSouthWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W.
        /// </summary>
        internal static string DirectionWest {
            get {
                return ResourceManager.GetString("DirectionWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find {0} on {1}.
        /// </summary>
        internal static string ErrorCannotFindField {
            get {
                return ResourceManager.GetString("ErrorCannotFindField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find original method {0}.
        /// </summary>
        internal static string ErrorCannotFindOriginalMethodFormat {
            get {
                return ResourceManager.GetString("ErrorCannotFindOriginalMethodFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find postfix method {0}.
        /// </summary>
        internal static string ErrorCannotFindPostfixMethodFormat {
            get {
                return ResourceManager.GetString("ErrorCannotFindPostfixMethodFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find prefix method {0}.
        /// </summary>
        internal static string ErrorCannotFindPrefixMethodFormat {
            get {
                return ResourceManager.GetString("ErrorCannotFindPrefixMethodFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load {0}. {1}.
        /// </summary>
        internal static string ErrorCannotLoadFormat {
            get {
                return ResourceManager.GetString("ErrorCannotLoadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save {0}. {1}.
        /// </summary>
        internal static string ErrorCannotSaveFormat {
            get {
                return ResourceManager.GetString("ErrorCannotSaveFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} seems corrupted. Please fix.
        /// </summary>
        internal static string ErrorCorruptedFileFormat {
            get {
                return ResourceManager.GetString("ErrorCorruptedFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} seems corrupted in {1}. Please fix.
        /// </summary>
        internal static string ErrorCorruptedPropertyFormat {
            get {
                return ResourceManager.GetString("ErrorCorruptedPropertyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create item!.
        /// </summary>
        internal static string ErrorFailedToCreateItem {
            get {
                return ResourceManager.GetString("ErrorFailedToCreateItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load item bundle!.
        /// </summary>
        internal static string ErrorFailedToLoadItemBundle {
            get {
                return ResourceManager.GetString("ErrorFailedToLoadItemBundle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not found!.
        /// </summary>
        internal static string ErrorFileNotFoundFormat {
            get {
                return ResourceManager.GetString("ErrorFileNotFoundFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid arguments.
        /// </summary>
        internal static string ErrorInvalidArguments {
            get {
                return ResourceManager.GetString("ErrorInvalidArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No bot found!.
        /// </summary>
        internal static string ErrorNoBotFound {
            get {
                return ResourceManager.GetString("ErrorNoBotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No template found!.
        /// </summary>
        internal static string ErrorNoTemplateFound {
            get {
                return ResourceManager.GetString("ErrorNoTemplateFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} bots, be more specific.
        /// </summary>
        internal static string ErrorTooManyBotsFormat {
            get {
                return ResourceManager.GetString("ErrorTooManyBotsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} templates, be more specific.
        /// </summary>
        internal static string ErrorTooManyTemplatesFormat {
            get {
                return ResourceManager.GetString("ErrorTooManyTemplatesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported type: {0}.
        /// </summary>
        internal static string ErrorUnsupportedTypeFormat {
            get {
                return ResourceManager.GetString("ErrorUnsupportedTypeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aimbot. Automatic aiming and/or shooting (SilentAim)..
        /// </summary>
        internal static string FeatureAimbotDescription {
            get {
                return ResourceManager.GetString("FeatureAimbotDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aimbot.
        /// </summary>
        internal static string FeatureAimbotName {
            get {
                return ResourceManager.GetString("FeatureAimbotName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlimited ammo..
        /// </summary>
        internal static string FeatureAmmunitionDescription {
            get {
                return ResourceManager.GetString("FeatureAmmunitionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ammo.
        /// </summary>
        internal static string FeatureAmmunitionName {
            get {
                return ResourceManager.GetString("FeatureAmmunitionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force all guns (even bolt action guns) to use automatic firing mode with customizable fire rate..
        /// </summary>
        internal static string FeatureAutomaticGunDescription {
            get {
                return ResourceManager.GetString("FeatureAutomaticGunDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to autogun.
        /// </summary>
        internal static string FeatureAutomaticGunName {
            get {
                return ResourceManager.GetString("FeatureAutomaticGunName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free camera with fast mode and teleportation..
        /// </summary>
        internal static string FeatureCameraDescription {
            get {
                return ResourceManager.GetString("FeatureCameraDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to camera.
        /// </summary>
        internal static string FeatureCameraName {
            get {
                return ResourceManager.GetString("FeatureCameraName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This main popup window..
        /// </summary>
        internal static string FeatureCommandsDescription {
            get {
                return ResourceManager.GetString("FeatureCommandsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to commands.
        /// </summary>
        internal static string FeatureCommandsName {
            get {
                return ResourceManager.GetString("FeatureCommandsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EFT Trainer.
        /// </summary>
        internal static string FeatureCommandsTitle {
            get {
                return ResourceManager.GetString("FeatureCommandsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crosshair with customizable size, color, thickness and auto-hide feature when aiming..
        /// </summary>
        internal static string FeatureCrosshairDescription {
            get {
                return ResourceManager.GetString("FeatureCrosshairDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crosshair.
        /// </summary>
        internal static string FeatureCrosshairName {
            get {
                return ResourceManager.GetString("FeatureCrosshairName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum durability of items..
        /// </summary>
        internal static string FeatureDurabilityDescription {
            get {
                return ResourceManager.GetString("FeatureDurabilityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to durability.
        /// </summary>
        internal static string FeatureDurabilityName {
            get {
                return ResourceManager.GetString("FeatureDurabilityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All items already examined. Instant search..
        /// </summary>
        internal static string FeatureExamineDescription {
            get {
                return ResourceManager.GetString("FeatureExamineDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to examine.
        /// </summary>
        internal static string FeatureExamineName {
            get {
                return ResourceManager.GetString("FeatureExamineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exfiltration points with customizable colors given eligibility, status filter, distance..
        /// </summary>
        internal static string FeatureExfiltrationPointsDescription {
            get {
                return ResourceManager.GetString("FeatureExfiltrationPointsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}).
        /// </summary>
        internal static string FeatureExfiltrationPointsEligibleFormat {
            get {
                return ResourceManager.GetString("FeatureExfiltrationPointsEligibleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exfil.
        /// </summary>
        internal static string FeatureExfiltrationPointsName {
            get {
                return ResourceManager.GetString("FeatureExfiltrationPointsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        internal static string FeatureExfiltrationPointsStatusActivate {
            get {
                return ResourceManager.GetString("FeatureExfiltrationPointsStatusActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        internal static string FeatureExfiltrationPointsStatusClosed {
            get {
                return ResourceManager.GetString("FeatureExfiltrationPointsStatusClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string FeatureExfiltrationPointsStatusOpen {
            get {
                return ResourceManager.GetString("FeatureExfiltrationPointsStatusOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        internal static string FeatureExfiltrationPointsStatusPending {
            get {
                return ResourceManager.GetString("FeatureExfiltrationPointsStatusPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirement.
        /// </summary>
        internal static string FeatureExfiltrationPointsStatusRequirement {
            get {
                return ResourceManager.GetString("FeatureExfiltrationPointsStatusRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer.
        /// </summary>
        internal static string FeatureExfiltrationPointsStatusTimer {
            get {
                return ResourceManager.GetString("FeatureExfiltrationPointsStatusTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shoot through wall/helmet/vest/material with maximum penetration and minimal deviation/ricochet..
        /// </summary>
        internal static string FeatureFeatureWallShootDescription {
            get {
                return ResourceManager.GetString("FeatureFeatureWallShootDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Field Of View (FOV)..
        /// </summary>
        internal static string FeatureFovChangerDescription {
            get {
                return ResourceManager.GetString("FeatureFovChangerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fovchanger.
        /// </summary>
        internal static string FeatureFovChangerName {
            get {
                return ResourceManager.GetString("FeatureFovChangerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh all game information for other features..
        /// </summary>
        internal static string FeatureGameStateDescription {
            get {
                return ResourceManager.GetString("FeatureGameStateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gamestate.
        /// </summary>
        internal static string FeatureGameStateName {
            get {
                return ResourceManager.GetString("FeatureGameStateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop bots from seeing you..
        /// </summary>
        internal static string FeatureGhostDescription {
            get {
                return ResourceManager.GetString("FeatureGhostDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ghost.
        /// </summary>
        internal static string FeatureGhostName {
            get {
                return ResourceManager.GetString("FeatureGhostName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grenades outline..
        /// </summary>
        internal static string FeatureGrenadesDescription {
            get {
                return ResourceManager.GetString("FeatureGrenadesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grenade.
        /// </summary>
        internal static string FeatureGrenadesName {
            get {
                return ResourceManager.GetString("FeatureGrenadesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full health, prevent any damage (so even when falling), keep energy and hydration at maximum..
        /// </summary>
        internal static string FeatureHealthDescription {
            get {
                return ResourceManager.GetString("FeatureHealthDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to health.
        /// </summary>
        internal static string FeatureHealthName {
            get {
                return ResourceManager.GetString("FeatureHealthName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hit markers (hit, armor, health with configurable colors)..
        /// </summary>
        internal static string FeatureHitsDescription {
            get {
                return ResourceManager.GetString("FeatureHitsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hits.
        /// </summary>
        internal static string FeatureHitsName {
            get {
                return ResourceManager.GetString("FeatureHitsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0},{1}).
        /// </summary>
        internal static string FeatureHudCoordinatesFormat {
            get {
                return ResourceManager.GetString("FeatureHudCoordinatesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HUD (compass, ammo left in chamber / magazine, fire mode, coordinates)..
        /// </summary>
        internal static string FeatureHudDescription {
            get {
                return ResourceManager.GetString("FeatureHudDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hud.
        /// </summary>
        internal static string FeatureHudName {
            get {
                return ResourceManager.GetString("FeatureHudName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - .
        /// </summary>
        internal static string FeatureHudSeparator {
            get {
                return ResourceManager.GetString("FeatureHudSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}+{1}/{2} [{3}].
        /// </summary>
        internal static string FeatureHudWeaponFormat {
            get {
                return ResourceManager.GetString("FeatureHudWeaponFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change distance for loot/door interaction..
        /// </summary>
        internal static string FeatureInteractDescription {
            get {
                return ResourceManager.GetString("FeatureInteractDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to interact.
        /// </summary>
        internal static string FeatureInteractName {
            get {
                return ResourceManager.GetString("FeatureInteractName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List all lootable items and track any item by name or rarity or in-game wishlist in raid (even in containers and corpses). Use track and tracklist commands to control display..
        /// </summary>
        internal static string FeatureLootItemsDescription {
            get {
                return ResourceManager.GetString("FeatureLootItemsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loot.
        /// </summary>
        internal static string FeatureLootItemsName {
            get {
                return ResourceManager.GetString("FeatureLootItemsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full screen map with radar esp..
        /// </summary>
        internal static string FeatureMapDescription {
            get {
                return ResourceManager.GetString("FeatureMapDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to map.
        /// </summary>
        internal static string FeatureMapName {
            get {
                return ResourceManager.GetString("FeatureMapName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night vision..
        /// </summary>
        internal static string FeatureNightVisionDescription {
            get {
                return ResourceManager.GetString("FeatureNightVisionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to night.
        /// </summary>
        internal static string FeatureNightVisionName {
            get {
                return ResourceManager.GetString("FeatureNightVisionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No physical collisions, making you immune to bullets, grenades and barbed wires..
        /// </summary>
        internal static string FeatureNoCollisionDescription {
            get {
                return ResourceManager.GetString("FeatureNoCollisionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nocoll.
        /// </summary>
        internal static string FeatureNoCollisionName {
            get {
                return ResourceManager.GetString("FeatureNoCollisionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No weapon malfunctions: no misfires or failures to eject or feed. No jammed bolts or overheating..
        /// </summary>
        internal static string FeatureNoMalfunctionsDescription {
            get {
                return ResourceManager.GetString("FeatureNoMalfunctionsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nomal.
        /// </summary>
        internal static string FeatureNoMalfunctionsName {
            get {
                return ResourceManager.GetString("FeatureNoMalfunctionsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No recoil..
        /// </summary>
        internal static string FeatureNoRecoilDescription {
            get {
                return ResourceManager.GetString("FeatureNoRecoilDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to norecoil.
        /// </summary>
        internal static string FeatureNoRecoilName {
            get {
                return ResourceManager.GetString("FeatureNoRecoilName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No sway..
        /// </summary>
        internal static string FeatureNoSwayDescription {
            get {
                return ResourceManager.GetString("FeatureNoSwayDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nosway.
        /// </summary>
        internal static string FeatureNoSwayName {
            get {
                return ResourceManager.GetString("FeatureNoSwayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No visor, so even when using a face shield-visor you won&apos;t see it..
        /// </summary>
        internal static string FeatureNoVisorDescription {
            get {
                return ResourceManager.GetString("FeatureNoVisorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to novisor.
        /// </summary>
        internal static string FeatureNoVisorName {
            get {
                return ResourceManager.GetString("FeatureNoVisorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallhack (you&apos;ll see Bear/Boss/Cultist/Scav/Usec with configurable colors through walls). Charms, boxes, info (weapon and health), skeletons and distance..
        /// </summary>
        internal static string FeaturePlayersDescription {
            get {
                return ResourceManager.GetString("FeaturePlayersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}% {2}.
        /// </summary>
        internal static string FeaturePlayersFormat {
            get {
                return ResourceManager.GetString("FeaturePlayersFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wallhack.
        /// </summary>
        internal static string FeaturePlayersName {
            get {
                return ResourceManager.GetString("FeaturePlayersName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}m].
        /// </summary>
        internal static string FeaturePointOfInterestsDistanceFormat {
            get {
                return ResourceManager.GetString("FeaturePointOfInterestsDistanceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} {2}.
        /// </summary>
        internal static string FeaturePointOfInterestsFormat {
            get {
                return ResourceManager.GetString("FeaturePointOfInterestsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt; In {0} {1}.
        /// </summary>
        internal static string FeaturePointOfInterestsGroupFormat {
            get {
                return ResourceManager.GetString("FeaturePointOfInterestsGroupFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (in {0}).
        /// </summary>
        internal static string FeaturePointOfInterestsOwnerFormat {
            get {
                return ResourceManager.GetString("FeaturePointOfInterestsOwnerFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations for taking/placing quest items. Only items related to your started quests are displayed..
        /// </summary>
        internal static string FeatureQuestsDescription {
            get {
                return ResourceManager.GetString("FeatureQuestsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}).
        /// </summary>
        internal static string FeatureQuestsFormat {
            get {
                return ResourceManager.GetString("FeatureQuestsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quest.
        /// </summary>
        internal static string FeatureQuestsName {
            get {
                return ResourceManager.GetString("FeatureQuestsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick-throw grenades..
        /// </summary>
        internal static string FeatureQuickTrowDescription {
            get {
                return ResourceManager.GetString("FeatureQuickTrowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quickthrow.
        /// </summary>
        internal static string FeatureQuickTrowName {
            get {
                return ResourceManager.GetString("FeatureQuickTrowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2D radar..
        /// </summary>
        internal static string FeatureRadarDescription {
            get {
                return ResourceManager.GetString("FeatureRadarDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to radar.
        /// </summary>
        internal static string FeatureRadarName {
            get {
                return ResourceManager.GetString("FeatureRadarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [summary].
        /// </summary>
        internal static string FeatureRendererSummary {
            get {
                return ResourceManager.GetString("FeatureRendererSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to EFT-Trainer !.
        /// </summary>
        internal static string FeatureRendererWelcome {
            get {
                return ResourceManager.GetString("FeatureRendererWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All skills to Elite level (51) and all weapons mastering to level 3..
        /// </summary>
        internal static string FeatureSkillsDescription {
            get {
                return ResourceManager.GetString("FeatureSkillsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to skills.
        /// </summary>
        internal static string FeatureSkillsName {
            get {
                return ResourceManager.GetString("FeatureSkillsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed boost to be able to go through walls/objects, or to move faster. Be careful to not kill yourself..
        /// </summary>
        internal static string FeatureSpeedDescription {
            get {
                return ResourceManager.GetString("FeatureSpeedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to speed.
        /// </summary>
        internal static string FeatureSpeedName {
            get {
                return ResourceManager.GetString("FeatureSpeedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlimited stamina..
        /// </summary>
        internal static string FeatureStaminaDescription {
            get {
                return ResourceManager.GetString("FeatureStaminaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stamina.
        /// </summary>
        internal static string FeatureStaminaName {
            get {
                return ResourceManager.GetString("FeatureStaminaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden/special stashes like buried barrels, ground caches, air drops or corpses..
        /// </summary>
        internal static string FeatureStashDescription {
            get {
                return ResourceManager.GetString("FeatureStashDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stash.
        /// </summary>
        internal static string FeatureStashName {
            get {
                return ResourceManager.GetString("FeatureStashName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thermal vision..
        /// </summary>
        internal static string FeatureThermalVisionDescription {
            get {
                return ResourceManager.GetString("FeatureThermalVisionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thermal.
        /// </summary>
        internal static string FeatureThermalVisionName {
            get {
                return ResourceManager.GetString("FeatureThermalVisionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summon train on compatible maps like Reserve or Lighthouse..
        /// </summary>
        internal static string FeatureTrainDescription {
            get {
                return ResourceManager.GetString("FeatureTrainDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to train.
        /// </summary>
        internal static string FeatureTrainName {
            get {
                return ResourceManager.GetString("FeatureTrainName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wallshoot.
        /// </summary>
        internal static string FeatureWallShootName {
            get {
                return ResourceManager.GetString("FeatureWallShootName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear weather..
        /// </summary>
        internal static string FeatureWeatherDescription {
            get {
                return ResourceManager.GetString("FeatureWeatherDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weather.
        /// </summary>
        internal static string FeatureWeatherName {
            get {
                return ResourceManager.GetString("FeatureWeatherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Door/Keycard reader/Car unlocker..
        /// </summary>
        internal static string FeatureWorldInteractiveObjectsDescription {
            get {
                return ResourceManager.GetString("FeatureWorldInteractiveObjectsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to opener.
        /// </summary>
        internal static string FeatureWorldInteractiveObjectsName {
            get {
                return ResourceManager.GetString("FeatureWorldInteractiveObjectsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armor-damage color.
        /// </summary>
        internal static string PropertyArmorDamageColor {
            get {
                return ResourceManager.GetString("PropertyArmorDamageColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backward.
        /// </summary>
        internal static string PropertyBackward {
            get {
                return ResourceManager.GetString("PropertyBackward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bear colors.
        /// </summary>
        internal static string PropertyBearColors {
            get {
                return ResourceManager.GetString("PropertyBearColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border color.
        /// </summary>
        internal static string PropertyBorderColor {
            get {
                return ResourceManager.GetString("PropertyBorderColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boss colors.
        /// </summary>
        internal static string PropertyBossColors {
            get {
                return ResourceManager.GetString("PropertyBossColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box thickness.
        /// </summary>
        internal static string PropertyBoxThickness {
            get {
                return ResourceManager.GetString("PropertyBoxThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache time (sec).
        /// </summary>
        internal static string PropertyCacheTimeInSec {
            get {
                return ResourceManager.GetString("PropertyCacheTimeInSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera offset.
        /// </summary>
        internal static string PropertyCameraOffset {
            get {
                return ResourceManager.GetString("PropertyCameraOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change time.
        /// </summary>
        internal static string PropertyChangeTime {
            get {
                return ResourceManager.GetString("PropertyChangeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string PropertyColor {
            get {
                return ResourceManager.GetString("PropertyColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cultist colors.
        /// </summary>
        internal static string PropertyCultistColors {
            get {
                return ResourceManager.GetString("PropertyCultistColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display time.
        /// </summary>
        internal static string PropertyDisplayTime {
            get {
                return ResourceManager.GetString("PropertyDisplayTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        internal static string PropertyDistance {
            get {
                return ResourceManager.GetString("PropertyDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eligible color.
        /// </summary>
        internal static string PropertyEligibleColor {
            get {
                return ResourceManager.GetString("PropertyEligibleColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string PropertyEnabled {
            get {
                return ResourceManager.GetString("PropertyEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fade-out time.
        /// </summary>
        internal static string PropertyFadeOutTime {
            get {
                return ResourceManager.GetString("PropertyFadeOutTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast mode.
        /// </summary>
        internal static string PropertyFastMode {
            get {
                return ResourceManager.GetString("PropertyFastMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast movement speed.
        /// </summary>
        internal static string PropertyFastMovementSpeed {
            get {
                return ResourceManager.GetString("PropertyFastMovementSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food / water.
        /// </summary>
        internal static string PropertyFoodWater {
            get {
                return ResourceManager.GetString("PropertyFoodWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward.
        /// </summary>
        internal static string PropertyForward {
            get {
                return ResourceManager.GetString("PropertyForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FOV.
        /// </summary>
        internal static string PropertyFov {
            get {
                return ResourceManager.GetString("PropertyFov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FOV circle color.
        /// </summary>
        internal static string PropertyFovCircleColor {
            get {
                return ResourceManager.GetString("PropertyFovCircleColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FOV circle thickness.
        /// </summary>
        internal static string PropertyFovCircleThickness {
            get {
                return ResourceManager.GetString("PropertyFovCircleThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FOV radius.
        /// </summary>
        internal static string PropertyFovRadius {
            get {
                return ResourceManager.GetString("PropertyFovRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free look sensitivity.
        /// </summary>
        internal static string PropertyFreeLookSensitivity {
            get {
                return ResourceManager.GetString("PropertyFreeLookSensitivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grouping Color.
        /// </summary>
        internal static string PropertyGroupingColor {
            get {
                return ResourceManager.GetString("PropertyGroupingColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health-damage color.
        /// </summary>
        internal static string PropertyHealthDamageColor {
            get {
                return ResourceManager.GetString("PropertyHealthDamageColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide when aiming.
        /// </summary>
        internal static string PropertyHideWhenAiming {
            get {
                return ResourceManager.GetString("PropertyHideWhenAiming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hit-marker color.
        /// </summary>
        internal static string PropertyHitMarkerColor {
            get {
                return ResourceManager.GetString("PropertyHitMarkerColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info color.
        /// </summary>
        internal static string PropertyInfoColor {
            get {
                return ResourceManager.GetString("PropertyInfoColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intensity.
        /// </summary>
        internal static string PropertyIntensity {
            get {
                return ResourceManager.GetString("PropertyIntensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        internal static string PropertyKey {
            get {
                return ResourceManager.GetString("PropertyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        internal static string PropertyLeft {
            get {
                return ResourceManager.GetString("PropertyLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marksman colors.
        /// </summary>
        internal static string PropertyMarksmanColors {
            get {
                return ResourceManager.GetString("PropertyMarksmanColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum distance.
        /// </summary>
        internal static string PropertyMaximumDistance {
            get {
                return ResourceManager.GetString("PropertyMaximumDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movement speed.
        /// </summary>
        internal static string PropertyMovementSpeed {
            get {
                return ResourceManager.GetString("PropertyMovementSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not eligible color.
        /// </summary>
        internal static string PropertyNotEligibleColor {
            get {
                return ResourceManager.GetString("PropertyNotEligibleColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not shootable colors.
        /// </summary>
        internal static string PropertyNotShootableColors {
            get {
                return ResourceManager.GetString("PropertyNotShootableColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radar background.
        /// </summary>
        internal static string PropertyRadarBackground {
            get {
                return ResourceManager.GetString("PropertyRadarBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radar crosshair.
        /// </summary>
        internal static string PropertyRadarCrosshair {
            get {
                return ResourceManager.GetString("PropertyRadarCrosshair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radar percentage.
        /// </summary>
        internal static string PropertyRadarPercentage {
            get {
                return ResourceManager.GetString("PropertyRadarPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radar range.
        /// </summary>
        internal static string PropertyRadarRange {
            get {
                return ResourceManager.GetString("PropertyRadarRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range.
        /// </summary>
        internal static string PropertyRange {
            get {
                return ResourceManager.GetString("PropertyRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        internal static string PropertyRate {
            get {
                return ResourceManager.GetString("PropertyRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove negative effects.
        /// </summary>
        internal static string PropertyRemoveNegativeEffects {
            get {
                return ResourceManager.GetString("PropertyRemoveNegativeEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        internal static string PropertyRight {
            get {
                return ResourceManager.GetString("PropertyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rogue-Usec colors.
        /// </summary>
        internal static string PropertyRogueUsecColors {
            get {
                return ResourceManager.GetString("PropertyRogueUsecColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scav-assault colors.
        /// </summary>
        internal static string PropertyScavAssaultColors {
            get {
                return ResourceManager.GetString("PropertyScavAssaultColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scav colors.
        /// </summary>
        internal static string PropertyScavColors {
            get {
                return ResourceManager.GetString("PropertyScavColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scav-raider colors.
        /// </summary>
        internal static string PropertyScavRaiderColors {
            get {
                return ResourceManager.GetString("PropertyScavRaiderColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search inside containers.
        /// </summary>
        internal static string PropertySearchInsideContainers {
            get {
                return ResourceManager.GetString("PropertySearchInsideContainers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search inside corpses.
        /// </summary>
        internal static string PropertySearchInsideCorpses {
            get {
                return ResourceManager.GetString("PropertySearchInsideCorpses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shootable colors.
        /// </summary>
        internal static string PropertyShootableColors {
            get {
                return ResourceManager.GetString("PropertyShootableColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show armor damage.
        /// </summary>
        internal static string PropertyShowArmorDamage {
            get {
                return ResourceManager.GetString("PropertyShowArmorDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Bosses.
        /// </summary>
        internal static string PropertyShowBosses {
            get {
                return ResourceManager.GetString("PropertyShowBosses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show boxes.
        /// </summary>
        internal static string PropertyShowBoxes {
            get {
                return ResourceManager.GetString("PropertyShowBoxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show charms.
        /// </summary>
        internal static string PropertyShowCharms {
            get {
                return ResourceManager.GetString("PropertyShowCharms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show compass.
        /// </summary>
        internal static string PropertyShowCompass {
            get {
                return ResourceManager.GetString("PropertyShowCompass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show containers.
        /// </summary>
        internal static string PropertyShowContainers {
            get {
                return ResourceManager.GetString("PropertyShowContainers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show coordinates.
        /// </summary>
        internal static string PropertyShowCoordinates {
            get {
                return ResourceManager.GetString("PropertyShowCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show corpses.
        /// </summary>
        internal static string PropertyShowCorpses {
            get {
                return ResourceManager.GetString("PropertyShowCorpses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Cultists.
        /// </summary>
        internal static string PropertyShowCultists {
            get {
                return ResourceManager.GetString("PropertyShowCultists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show eligible.
        /// </summary>
        internal static string PropertyShowEligible {
            get {
                return ResourceManager.GetString("PropertyShowEligible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show fov circle.
        /// </summary>
        internal static string PropertyShowFovCircle {
            get {
                return ResourceManager.GetString("PropertyShowFovCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show health-damage.
        /// </summary>
        internal static string PropertyShowHealthDamage {
            get {
                return ResourceManager.GetString("PropertyShowHealthDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Hit-marker.
        /// </summary>
        internal static string PropertyShowHitMarker {
            get {
                return ResourceManager.GetString("PropertyShowHitMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show infos.
        /// </summary>
        internal static string PropertyShowInfos {
            get {
                return ResourceManager.GetString("PropertyShowInfos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show map.
        /// </summary>
        internal static string PropertyShowMap {
            get {
                return ResourceManager.GetString("PropertyShowMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Marksmen.
        /// </summary>
        internal static string PropertyShowMarksmen {
            get {
                return ResourceManager.GetString("PropertyShowMarksmen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show not eligible.
        /// </summary>
        internal static string PropertyShowNotEligible {
            get {
                return ResourceManager.GetString("PropertyShowNotEligible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show not shootable.
        /// </summary>
        internal static string PropertyShowNotShootable {
            get {
                return ResourceManager.GetString("PropertyShowNotShootable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show players.
        /// </summary>
        internal static string PropertyShowPlayers {
            get {
                return ResourceManager.GetString("PropertyShowPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show prices.
        /// </summary>
        internal static string PropertyShowPrices {
            get {
                return ResourceManager.GetString("PropertyShowPrices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Rogues.
        /// </summary>
        internal static string PropertyShowRogues {
            get {
                return ResourceManager.GetString("PropertyShowRogues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Scav-assaults.
        /// </summary>
        internal static string PropertyShowScavAssaults {
            get {
                return ResourceManager.GetString("PropertyShowScavAssaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Scav-raiders.
        /// </summary>
        internal static string PropertyShowScavRaiders {
            get {
                return ResourceManager.GetString("PropertyShowScavRaiders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Scavs.
        /// </summary>
        internal static string PropertyShowScavs {
            get {
                return ResourceManager.GetString("PropertyShowScavs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show shootable.
        /// </summary>
        internal static string PropertyShowShootable {
            get {
                return ResourceManager.GetString("PropertyShowShootable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show skeletons.
        /// </summary>
        internal static string PropertyShowSkeletons {
            get {
                return ResourceManager.GetString("PropertyShowSkeletons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silent aim.
        /// </summary>
        internal static string PropertySilentAim {
            get {
                return ResourceManager.GetString("PropertySilentAim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silent aim next-shot-delay.
        /// </summary>
        internal static string PropertySilentAimNextShotDelay {
            get {
                return ResourceManager.GetString("PropertySilentAimNextShotDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silent aim speed-factor.
        /// </summary>
        internal static string PropertySilentAimSpeedFactor {
            get {
                return ResourceManager.GetString("PropertySilentAimSpeedFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string PropertySize {
            get {
                return ResourceManager.GetString("PropertySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skeleton thickness.
        /// </summary>
        internal static string PropertySkeletonThickness {
            get {
                return ResourceManager.GetString("PropertySkeletonThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoothness.
        /// </summary>
        internal static string PropertySmoothness {
            get {
                return ResourceManager.GetString("PropertySmoothness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status filter.
        /// </summary>
        internal static string PropertyStatusFilter {
            get {
                return ResourceManager.GetString("PropertyStatusFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teleport.
        /// </summary>
        internal static string PropertyTeleport {
            get {
                return ResourceManager.GetString("PropertyTeleport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thickness.
        /// </summary>
        internal static string PropertyThickness {
            get {
                return ResourceManager.GetString("PropertyThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Auto Wishlist.
        /// </summary>
        internal static string PropertyTrackAutoWishlist {
            get {
                return ResourceManager.GetString("PropertyTrackAutoWishlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example: [&quot;foo&quot;, &quot;bar&quot;] or with extended properties: [{&quot;Name&quot;:&quot;foo&quot;,&quot;Color&quot;:[1.0,0.0,0.0,1.0]},{&quot;Name&quot;:&quot;bar&quot;,&quot;Color&quot;:[1.0,1.0,1.0,0.8],&quot;Rarity&quot;:&quot;Rare&quot;}].
        /// </summary>
        internal static string PropertyTrackedNamesComment {
            get {
                return ResourceManager.GetString("PropertyTrackedNamesComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Wishlist.
        /// </summary>
        internal static string PropertyTrackWishlist {
            get {
                return ResourceManager.GetString("PropertyTrackWishlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usec colors.
        /// </summary>
        internal static string PropertyUsecColors {
            get {
                return ResourceManager.GetString("PropertyUsecColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vitals only.
        /// </summary>
        internal static string PropertyVitalsOnly {
            get {
                return ResourceManager.GetString("PropertyVitalsOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        internal static string PropertyX {
            get {
                return ResourceManager.GetString("PropertyX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XRay-Vision.
        /// </summary>
        internal static string PropertyXRayVision {
            get {
                return ResourceManager.GetString("PropertyXRayVision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        internal static string PropertyY {
            get {
                return ResourceManager.GetString("PropertyY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to off.
        /// </summary>
        internal static string TextOff {
            get {
                return ResourceManager.GetString("TextOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on.
        /// </summary>
        internal static string TextOn {
            get {
                return ResourceManager.GetString("TextOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ------.
        /// </summary>
        internal static string TextSeparator {
            get {
                return ResourceManager.GetString("TextSeparator", resourceCulture);
            }
        }
    }
}
